# Generated by Django 5.2.4 on 2025-07-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
    ]
