# Generated by Django 5.2.4 on 2025-07-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_fill_email_for_existing_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='temp@email.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
