# Generated by Django 5.2.4 on 2025-07-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_remove_teacher_passwd_teacher_id_and_more"),
        ("teachers", "0002_rename_name_teacher_teacher_name_teacher_id_and_more"),
    ]

    operations = []
